# Creating Tensors
we create a tensor from a list or a numpy array


### tf.convert_to_tensor() - to convert a list or numpy array into a Tensor

In [ ]:
a = np.array([1, 2, 3], dtype = np.int32)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


### tf.ones() - Create a tensor of 1s of shape (2, 3) 


In [ ]:
t_ones = tf.ones((2,3))
print(t_ones.shape)

(2, 3)


### .numpy()  - to access the values that a tensor refers to

In [ ]:
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

### tf.constant() - create a Tensor of Constant values

In [ ]:
const = tf.constant([1.2, 4], dtype = tf.float32)
print(const)

tf.Tensor([1.2       4.        3.1415927], shape=(3,), dtype=float32)


# Shapes & Dimensions

In [ ]:
matrix = tf.constant([[1,2,3],
                      [4,5,6]], dtype = tf.float32)

x = matrix.numpy()

print(a)
print()
print('shape:', x.shape)
print('dimension/axes:', x.ndim)

[[1. 2. 3.]
 [4. 5. 6.]]

shape: (2, 3)
dimension/axes: 2


## 0D Tensor - Scalar

In [ ]:
import numpy as np
x = np.array(3)

print('shape:', x.shape)
print('dimension/axes:', x.ndim)

shape: ()
dimension/axes: 0


## 1D Tensor - Vector

In [ ]:
x = np.array([12,3,6,14])

print('shape:', x.shape)
print('dimension/axes:', x.ndim)

shape: (4,)
dimension/axes: 1


## 2D Tensor - Matrix

In [ ]:
x= np.array ([[1, 2, 3],
              [6, 7, 4],
              [2, 12, 5]])

print('shape:', x.shape)
print('dimension/axes:', x.ndim)

shape: (3, 3)
dimension/axes: 2


## 3D Tensor

In [ ]:
x = np.array([ [[5, 12 ],
                [2, 32 ]],
              
               [[5, 1 ],
                [6, 7 ]],
              
               [[2, 3 ],
                [1, 7 ]]])

print('shape:', x.shape)
print('dimension/axes:', x.ndim)

shape: (3, 2, 2)
dimension/axes: 3


# Manipulate Data Type and Shape

### np.expand_dims() - add axis/dimension

In [ ]:
x= np.array ([[1, 2, 3],
              [6, 7, 4],
              [2, 12, 5]])

print('Before:\n''shape:', x.shape)
print('dimension/axes:', x.ndim)

a = np.expand_dims(x, axis = 0)

print('\nAfter:\n''shape:', a.shape)
print('dimension/axes:', a.ndim)

### np.newaxis - add axis/dimension

In [ ]:
x= np.array ([[1, 2, 3],
              [6, 7, 4],
              [2, 12, 5]])

print('Before:\n''shape:', x.shape)
print('dimension/axes:', x.ndim)

a = x[np.newaxis,...]

print('\nAfter:\n''shape:', a.shape)
print('dimension/axes:', a.ndim)

### tf.squeeze() - Remove Unnecessory Dimensions with size = 1

In [ ]:
t = tf.ones((3,1,2,1))
t_sqz = tf.squeeze(t, axis = (1,3))

print('before squeezed :', t.shape)
print('after squeezed :', t_sqz.shape)

NameError: name 'tf' is not defined

### tf.cast() - change data type of a tensor

In [ ]:
t = tf.constant([1,2,3], dtype = tf.int32)
t_new = tf.cast(t, tf.int64)
print(t.dtype)
print(t_new.dtype)

<dtype: 'int32'>
<dtype: 'int64'>


### tf.transpose() - Transpose a Tensor

In [ ]:
t = tf.constant([[1,3,5], [2,4,6]], dtype = tf.int32)
t_trans = tf.transpose(t)

print('t =\n', t.numpy(), '\n')
print('t_trans =\n', t_trans.numpy())

t =
 [[1 3 5]
 [2 4 6]] 

t_trans =
 [[1 2]
 [3 4]
 [5 6]]


### tf.reshape() - Reshape a Tensor

In [ ]:
t = tf.ones((6,))
t_reshape = tf.reshape(t, shape = (2,3))

print('t =', t.numpy(), '\n')
print('t_reshape =\n', t_reshape.numpy())

t = [1. 1. 1. 1. 1. 1.] 

t_reshape =
 [[1. 1. 1.]
 [1. 1. 1.]]


# Mathematical Operations

### tf.multiply() - element-wise product

In [ ]:
t1 = tf.constant([[1, 2, 3],
                 [4, 5, 6]], dtype = tf.float32)

t2 = tf.constant([[1, 2, 3],
                 [4, 5, 6]], dtype = tf.float32)

t = tf.multiply(t1, t2).numpy()
print(t)

[[ 1.  4.  9.]
 [16. 25. 36.]]


### tf.math.reduce_mean() - find mean along an axis

In [ ]:
t_axis0 = tf.math.reduce_mean(t1, axis = 0)
t_axis1 = tf.math.reduce_mean(t1, axis = 1)

print('t_axis0 =', t_axis0.numpy())
print('t_axis1 =', t_axis1.numpy())

t_axis0 = [2.5 3.5 4.5]
t_axis1 = [2. 5.]


### tf.math.reduce_sum() - find sum along an axis

In [ ]:
t_axis0 = tf.math.reduce_sum(t1, axis = 0)
t_axis1 = tf.math.reduce_sum(t1, axis = 1)

print('t_axis0 =', t_axis0.numpy())
print('t_axis1 =', t_axis1.numpy())

t_axis0 = [5. 7. 9.]
t_axis1 = [ 6. 15.]


### tf.math.reduce_std() - find standard deviation along an axis

In [ ]:
t_axis0 = tf.math.reduce_std(t1, axis = 0)
t_axis1 = tf.math.reduce_std(t1, axis = 1)

print('t_axis0 =', t_axis0.numpy())
print('t_axis1 =', t_axis1.numpy())

t_axis0 = [1.5 1.5 1.5]
t_axis1 = [0.8164966 0.8164966]


### tf.linalg.matmul() - Matrix-Matrix Multiplication

In [ ]:
# t1 x t2(transposed)
tb_trans = tf.linalg.matmul(t1, t2, transpose_b = True)

# t1(transposed) x t2
ta_trans = tf.linalg.matmul(t1, t2, transpose_a = True)

print('t1 x t2(transposed):\n', tb_trans.numpy(), '\n')
print('t1(transposed) x t2:\n', ta_trans.numpy())

t1 x t2(transposed):
 [[14. 32.]
 [32. 77.]] 

t1(transposed) x t2:
 [[17. 22. 27.]
 [22. 29. 36.]
 [27. 36. 45.]]


# Split, Stack & Concatenate Tensors

### tf.split() - Splitting Tensors

In [ ]:
t = tf.constant([1, 5, 13, 9, 23, 50], dtype = tf.float32)

# provide the number of splits
# num_or_size_splits - total number of tensors must be divisible by the number of splits
# in this case, total number of tensors = 6
# desired number of splits = 3
# therefore, 2 tensors in each split
t_split1 = tf.split(t, num_or_size_splits = 3)

for item in t_split1:
    print(item.numpy())
    
# tf.split() - provide the sizes of different splits
t_split2 = tf.split(t, num_or_size_splits = [4,2])

for item in t_split2:
    print(item.numpy())

[1. 5.]
[13.  9.]
[23. 50.]
[ 1.  5. 13.  9.]
[23. 50.]


### tf.concat()

In [ ]:
t1 = tf.ones((3,))
t2 = tf.zeros((2,))

t3 = tf.concat([t1,t2] , axis = 0)
print(t3.numpy())

[1. 1. 1. 0. 0.]


### tf.stack()

In [ ]:
t1 = tf.ones((3,))
t2 = tf.zeros((3,))

t3 = tf.stack([t1,t2] , axis = 0)
print(t3.numpy())

t4 = tf.stack([t1,t2] , axis = 1)
print(t4.numpy())

[[1. 1. 1.]
 [0. 0. 0.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]]
